image: docker:git

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  TEST_IMAGE: briar/ci-image-android:${CI_BUILD_REF_NAME}
  RELEASE_IMAGE: briar/ci-image-android:latest

before_script:
  - echo ${DOCKER_HUB_PASS} | docker login -u ${DOCKER_HUB_USER} --password-stdin

build:
  stage: build
  script:
    - docker build -t ${TEST_IMAGE} .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker run ${TEST_IMAGE} ./test.sh

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
    - tags

rebuild consumers:
  stage: release
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
    - "curl -X POST -F token=${REBUILD_EMULATOR} -F ref=master -F variables[RELEASE_TAG]=${CI_COMMIT_REF_NAME} https://code.briarproject.org/api/v4/projects/225/trigger/pipeline"
  only:
    - master
